Main server basis opgezet
PTS3-S34A/Main-Server pull request #1
Opened 2016-11-21 19:19 UTC by Laugslander

Main server applicatie in grote lijnen opgezet.

- Repository Design Pattern toegepast voor manipulatie MySQL database. 
- Database queries zoveel mogelijk geimplementeerd als stored procedures.

2016-11-21 19:49 UTC, Ranray requested changes

2016-11-21 19:49 UTC, Ranray commented on Soccar [Main-Server]/src/nl/soccar/library/SessionData.java
> +     * Constructor user for instantiation of a new SessionData object. A
Constructor **used**

2016-11-21 19:49 UTC, Ranray commented on Soccar [Main-Server]/src/nl/soccar/library/Statistics.java
> +    public String getGamesRatio() {
Waarom returned deze methode een String en niet gewoon een Double?

2016-11-21 19:49 UTC, Ranray commented on Soccar [Main-Server]/src/nl/soccar/mainserver/data/context/UserMySqlContext.java
> +            return false;
Graag de exception loggen, wordt op dit moment niets mee gedaan.

2016-11-21 19:49 UTC, Ranray commented on Soccar [Main-Server]/src/nl/soccar/mainserver/data/context/UserMySqlContext.java
> +        } catch (SQLException e) {
Graag de exception loggen, wordt op dit moment niets mee gedaan.

2016-11-21 19:49 UTC, Ranray commented on Soccar [Main-Server]/src/nl/soccar/mainserver/data/repository/UserRepository.java
> +     * Method that adds a new user to the persistency service.
Adds a new user to the persistency service.

2016-11-21 19:49 UTC, Ranray commented on Soccar [Main-Server]/src/nl/soccar/mainserver/data/repository/StatisticsRepository.java
> +     * persistency service.
Gets the game statistics of a player stored in the persistency service.

2016-11-21 19:49 UTC, Ranray commented on Soccar [Main-Server]/src/nl/soccar/mainserver/data/repository/StatisticsRepository.java
> +     * persistency service.
Increments the amount of games lost by a player stored in the persistency service.

2016-11-21 19:49 UTC, Ranray commented on Soccar [Main-Server]/src/nl/soccar/mainserver/data/repository/StatisticsRepository.java
> +     * persistency service.
Increments the amount of games won by a player stored in the persistency service.

2016-11-21 19:49 UTC, Ranray commented on Soccar [Main-Server]/src/nl/soccar/mainserver/data/repository/StatisticsRepository.java
> +     * the persistency service.
Adds a given amount of assists to the given player stored in the persistency service.

2016-11-21 19:49 UTC, Ranray commented on Soccar [Main-Server]/src/nl/soccar/mainserver/data/repository/StatisticsRepository.java
> +     * the persistency service.
Adds a given amount of goals to the given player stored in the persistency service.

2016-11-21 19:49 UTC, Ranray commented on Soccar [Main-Server]/src/nl/soccar/mainserver/data/repository/StatisticsRepository.java
> +     * the persistency service.
Increments the amount of games played by a player stored in the persistency service.

2016-11-21 19:49 UTC, Ranray commented on Soccar [Main-Server]/src/nl/soccar/mainserver/data/repository/StatisticsRepository.java
> +     * service.
Gets the game statistics of all players from the persistency service.

2016-11-21 19:49 UTC, Ranray commented on Soccar [Main-Server]/src/nl/soccar/mainserver/data/repository/UserRepository.java
> +     * persistency service.
Changes the privilege of the given player stored in the persistency service.

2016-11-21 19:49 UTC, Ranray commented on Soccar [Main-Server]/src/nl/soccar/mainserver/data/repository/UserRepository.java
> +     * the stored username.
Checks if a player exists in the persistency service based on the stored username.

2016-11-21 19:49 UTC, Ranray commented on Soccar [Main-Server]/src/nl/soccar/mainserver/data/repository/UserRepository.java
> +     * username stored in the persistency service.
Checks if the given hashed password belongs to the given username stored in the persistency service.

2016-11-21 19:49 UTC, Ranray commented on Soccar [Main-Server]/src/nl/soccar/mainserver/rmi/server/MainServer.java
> +     * gets the statistics data repository.
**G**ets the statistics data repository.

2016-11-21 19:49 UTC, Ranray commented on Soccar [Main-Server]/src/nl/soccar/mainserver/util/DatabaseUtilities.java
> +     * database connection.
Prepares an SQL query call to the database using the active database connection.

2016-11-21 19:49 UTC, Ranray commented on Soccar [Main-Server]/src/nl/soccar/mainserver/util/DatabaseUtilities.java
> +     * active database connection.
Prepares an SQL query statement to the database using the active database connection.

2016-11-21 19:49 UTC, Ranray commented on Soccar [Main-Server]/src/nl/soccar/mainserver/util/PasswordUtilities.java
> +     * algoritm.
Generates a random salt of 16 bytes based on the SHA1PRNG algoritm.

2016-11-21 19:49 UTC, Ranray commented on Soccar [Main-Server]/src/nl/soccar/mainserver/util/PasswordUtilities.java
> +     * byte array of 64 bytes.
Adds a salt to a hashed password and combines them as one byte array of 64 bytes.

2016-11-22 05:33 UTC, Laugslander commented
Gevraagde veranderingen doorgevoerd.

2016-11-22 07:40 UTC, Ranray approved these changes

2016-11-22 08:18 UTC, merged