Implemented game server pinging
PTS3-S34A/Main-Server pull request #16
Opened 2016-12-19 15:00 UTC by Laugslander

2016-12-19 15:00 UTC, TehMessiah commented on Soccar [Main-Server]/src/nl/soccar/mainserver/rmi/MainServerController.java
> +        timer.scheduleAtFixedRate(new TimerTask() {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) Reduce this anonymous class number of lines from 27 to at most 20, or make it a named class. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://194.135.91.67:9000/coding_rules#rule_key=squid%3AS1188)

2016-12-19 15:00 UTC, TehMessiah commented on Soccar [Main-Server]/src/nl/soccar/mainserver/rmi/MainServerController.java
> +                    serversToRemove.stream().forEach(s -> deregisterGameServer(s));
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) Replace this lambda with a method reference. (sonar.java.source not set. Assuming 8 or greater.) [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://194.135.91.67:9000/coding_rules#rule_key=squid%3AS1612)

2016-12-19 15:00 UTC, TehMessiah commented
SonarQube analysis reported 2 issues
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 1 major
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 1 minor

Watch the comments in this conversation to review them.

2016-12-20 07:42 UTC, BeeHiveJava requested changes

2016-12-20 07:42 UTC, BeeHiveJava commented on Soccar [Main-Server]/src/nl/soccar/mainserver/rmi/MainServerController.java
> +                    serversToRemove.stream().forEach(s -> deregisterGameServer(s));
Hij heeft gelijk! `forEach(MainServerController::deregisterGameServer)`

2016-12-20 08:20 UTC, TehMessiah commented on Soccar [Main-Server]/src/nl/soccar/mainserver/rmi/MainServerController.java
> +            serversToRemove.stream().forEach(s -> deregisterGameServer(s));
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) Replace this lambda with a method reference. (sonar.java.source not set. Assuming 8 or greater.) [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://194.135.91.67:9000/coding_rules#rule_key=squid%3AS1612)

2016-12-20 08:20 UTC, TehMessiah commented
SonarQube analysis reported 1 issue
* ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) 1 minor

Watch the comments in this conversation to review them.

2016-12-20 08:35 UTC, BeeHiveJava approved these changes

2016-12-20 08:35 UTC, merged